//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task3.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string DefaultCharacter {
            get {
                return ResourceManager.GetString("DefaultCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Please enter a numeric value: .
        /// </summary>
        internal static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Please enter a value greater than 0: .
        /// </summary>
        internal static string InputErrorIsNegative {
            get {
                return ResourceManager.GetString("InputErrorIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number N: .
        /// </summary>
        internal static string InputNumber {
            get {
                return ResourceManager.GetString("InputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use value default press key &apos;1&apos;, to enter press key &apos;2&apos;.
        /// </summary>
        internal static string InputSelection {
            get {
                return ResourceManager.GetString("InputSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the sides of the rectangle A and B through the gap: .
        /// </summary>
        internal static string InputSidesOfARect {
            get {
                return ResourceManager.GetString("InputSidesOfARect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the string: .
        /// </summary>
        internal static string InputTask11 {
            get {
                return ResourceManager.GetString("InputTask11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the first line: .
        /// </summary>
        internal static string InputTask121 {
            get {
                return ResourceManager.GetString("InputTask121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the second line: .
        /// </summary>
        internal static string InputTask122 {
            get {
                return ResourceManager.GetString("InputTask122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated value: .
        /// </summary>
        internal static string OutputGeneratedValue {
            get {
                return ResourceManager.GetString("OutputGeneratedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of items standing in even positions: .
        /// </summary>
        internal static string OutputTask10 {
            get {
                return ResourceManager.GetString("OutputTask10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average word length: .
        /// </summary>
        internal static string OutputTask11 {
            get {
                return ResourceManager.GetString("OutputTask11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result string: .
        /// </summary>
        internal static string OutputTask12 {
            get {
                return ResourceManager.GetString("OutputTask12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of non-negative elements: .
        /// </summary>
        internal static string OutputTask9 {
            get {
                return ResourceManager.GetString("OutputTask9", resourceCulture);
            }
        }
    }
}
